### PR TITLE
added github action example for downstream consumers

### PR DESCRIPTION
**Pull request by garethahealy**
it would be nice if this was provided as an action. couldn't see one already, so thought I'd provide.

@gahealy

### CODE REVIEW

**Comment by mmulholla** [comment]
Hi, thank you for providing. I have a couple of questions
- the action does not check the response from the verify command, can that be added?
- can the action be invoked from the makefile? If a PR can fail because of a check it is good for the developer to be bale to pre-run the test using make all.

**Comment by garethahealy** [comment]
1. i expected an error code to be returned from the process but it doesn't seem to work like that or am I missing something?

i.e.:

```
[root@e0be052ecf05 /]# /app/chart-verifier verify https://github.com/redhat-certification/chart-verifier/raw/main/pkg/chartverifier/checks/chart-0.1.0-v3.without-readme.tgz
Tool:
  verifier-version: 1.0.0
  chart-uri: https://github.com/redhat-certification/chart-verifier/raw/main/pkg/chartverifier/checks/chart-0.1.0-v3.without-readme.tgz
Chart:
  Name: testchart
  version: 1.16.0
ok: false

has-readme:
	ok: false
	reason: Chart does not have a README
is-helm-v3:
	ok: true
	reason: API version is V2, used in Helm 3
not-contains-crds:
	ok: true
	reason: Chart does not contain CRDs
helm-lint:
	ok: false
	reason: Helm lint has failed:  [INFO] Chart.yaml: icon is recommended

not-contain-csi-objects:
	ok: true
	reason: CSI objects do not exist
contains-test:
	ok: true
	reason: Chart test files exist
contains-values:
	ok: true
	reason: Values file exist
contains-values-schema:
	ok: true
	reason: Values schema file exist
has-minkubeversion:
	ok: true
	reason: Minimum Kubernetes version specified
[root@e0be052ecf05 /]# echo $?
0
```

I would of expected the above to return a non-zero code, as its "not ok"

2. invoke the github action from make? not that i know of. all the action is doing is re-running one of the tests already in the codebase, so not sure how that would be missed/different.

**Comment by garethahealy** [comment]
@jasperchui ; why was this PR closed?

**Comment by jasperchui** [comment]
@garethahealy Not sure it could've been by accident.  @dperaza4dustbit could you provide an update on this? Thanks.

**Comment by dperaza4dustbit** [comment]
Hello @garethahealy, not sure why the PR got closed, it could have part of a cleanup process given time of activity. But wanted to let you know that we are working with github actions team to implement this: https://github.com/redhat-actions/chart-verifier. Can you please review there and contribute if needed?

**Pull request closed without merging**
